// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIMYeXCJYbcKKmO_VvZt2NJCqLGZ-pEj4',
    appId: '1:734616283404:web:b2b4d7998a06e95020c129',
    messagingSenderId: '734616283404',
    projectId: 'doctor-74799',
    authDomain: 'doctor-74799.firebaseapp.com',
    storageBucket: 'doctor-74799.appspot.com',
    measurementId: 'G-RC9N7VV5HF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDADDGkgJBKRO2swERMvaX34fctYOobYtU',
    appId: '1:734616283404:android:a27a292b85f3f45320c129',
    messagingSenderId: '734616283404',
    projectId: 'doctor-74799',
    storageBucket: 'doctor-74799.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ2IBBrPp4W-TI7G3vhFc5G1sBE8XqiBg',
    appId: '1:734616283404:ios:fdbdb2423d9a80d220c129',
    messagingSenderId: '734616283404',
    projectId: 'doctor-74799',
    storageBucket: 'doctor-74799.appspot.com',
    iosBundleId: 'com.example.doctorAppp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ2IBBrPp4W-TI7G3vhFc5G1sBE8XqiBg',
    appId: '1:734616283404:ios:fdbdb2423d9a80d220c129',
    messagingSenderId: '734616283404',
    projectId: 'doctor-74799',
    storageBucket: 'doctor-74799.appspot.com',
    iosBundleId: 'com.example.doctorAppp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIMYeXCJYbcKKmO_VvZt2NJCqLGZ-pEj4',
    appId: '1:734616283404:web:61c3e131a6ec88e220c129',
    messagingSenderId: '734616283404',
    projectId: 'doctor-74799',
    authDomain: 'doctor-74799.firebaseapp.com',
    storageBucket: 'doctor-74799.appspot.com',
    measurementId: 'G-TEC2XRQ6E7',
  );
}
